<?php
//
// File generated by Dolibarr installer 22.0.4
// MODIFIED FOR RAILWAY NIXPACKS DEPLOYMENT
//

// --- 1. Konfigurasi URL & Path ---
$dolibarr_main_url_root = getenv('DOLI_URL_ROOT') ? getenv('DOLI_URL_ROOT') : 'http://localhost/dolibarr';

$dolibarr_main_document_root = getenv('DOLI_DOCUMENT_ROOT') ? getenv('DOLI_DOCUMENT_ROOT') : "C:/dolibarr/www/dolibarr/htdocs";

$dolibarr_main_url_root_alt = '/custom';
$dolibarr_main_document_root_alt = getenv('DOLI_DOCUMENT_ROOT') ? getenv('DOLI_DOCUMENT_ROOT') . '/custom' : "C:/dolibarr/www/dolibarr/htdocs/custom";

// DATA ROOT (/app/documents)
$dolibarr_main_data_root = getenv('DOLI_DATA_ROOT') ? getenv('DOLI_DATA_ROOT') : "C:/dolibarr/www/dolibarr/dolibarr_documents";

// --- 2. Konfigurasi Database (Sesuai Variabel Railway Anda) ---
$dolibarr_main_db_host = getenv('DOLI_DB_HOST') ? getenv('DOLI_DB_HOST') : 'localhost';
$dolibarr_main_db_port = getenv('DOLI_DB_PORT') ? getenv('DOLI_DB_PORT') : '3306';
$dolibarr_main_db_name = getenv('DOLI_DB_NAME') ? getenv('DOLI_DB_NAME') : 'dolibarr';
$dolibarr_main_db_user = getenv('DOLI_DB_USER') ? getenv('DOLI_DB_USER') : 'root';
$dolibarr_main_db_pass = getenv('DOLI_DB_PASSWORD') ? getenv('DOLI_DB_PASSWORD') : '';

$dolibarr_main_db_prefix = 'llx_';
$dolibarr_main_db_type = getenv('DOLI_DB_TYPE') ? getenv('DOLI_DB_TYPE') : 'mysqli';
$dolibarr_main_db_character_set = 'utf8';
$dolibarr_main_db_collation = 'utf8_unicode_ci';

// --- 3. Authentication & Security ---
$dolibarr_main_authentication = getenv('DOLI_AUTH') ? getenv('DOLI_AUTH') : 'dolibarr';

// Force HTTPS: Otomatis aktif jika di Railway
$dolibarr_main_force_https = '1';

// Production Mode: 1 = Aman (Hide Error), 0 = Dev
$dolibarr_main_prod = getenv('DOLI_PROD') ? getenv('DOLI_PROD') : '0';

$dolibarr_main_restrict_os_commands = 'mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck = '0';
$dolibarr_main_instance_unique_id = 'unique_id_generated_randomly';
$dolibarr_mailing_limit_sendbyweb = '0';
$dolibarr_mailing_limit_sendbycli = '0';

$dolibarr_main_distrib = 'railway';