<?php
//
// File generated by Dolibarr installer 22.0.4
// MODIFIED FOR HYBRID DEPLOYMENT (LOCAL WINDOWS + RAILWAY CLOUD)
//

// --- 1. Konfigurasi URL ---
$dolibarr_main_url_root = getenv('DOLIBARR_URL') ? getenv('DOLIBARR_URL') : 'http://localhost/dolibarr';

// --- 2. Konfigurasi Path Folder (PENTING) ---
// DOCUMENT ROOT (Folder htdocs)
$dolibarr_main_document_root = getenv('DOCUMENT_ROOT') ? getenv('DOCUMENT_ROOT') : "C:/dolibarr/www/dolibarr/htdocs";

// CUSTOM FOLDER (Opsional)
$dolibarr_main_url_root_alt = '/custom';
$dolibarr_main_document_root_alt = getenv('DOCUMENT_ROOT') ? getenv('DOCUMENT_ROOT') . '/custom' : "C:/dolibarr/www/dolibarr/htdocs/custom";

// DATA ROOT (Folder documents)
$dolibarr_main_data_root = getenv('DATA_ROOT') ? getenv('DATA_ROOT') : "C:/dolibarr/www/dolibarr/dolibarr_documents";

// --- 3. Konfigurasi Database ---
$dolibarr_main_db_host = getenv('DB_HOST') ? getenv('DB_HOST') : 'localhost';
$dolibarr_main_db_port = getenv('DB_PORT') ? getenv('DB_PORT') : '3306';
$dolibarr_main_db_name = getenv('DB_NAME') ? getenv('DB_NAME') : 'dolibarr';
$dolibarr_main_db_user = getenv('DB_USER') ? getenv('DB_USER') : 'root';

$dolibarr_main_db_pass = getenv('DB_PASSWORD') ? getenv('DB_PASSWORD') : '';


$dolibarr_main_db_prefix = 'llx_';
$dolibarr_main_db_type = 'mysqli';
$dolibarr_main_db_character_set = 'utf8';
$dolibarr_main_db_collation = 'utf8_unicode_ci';

// --- 4. Authentication & Security ---
$dolibarr_main_authentication = 'dolibarr';

// Force HTTPS: Aktifkan (1) jika di Railway (biasanya via ENV), 0 jika di localhost
$dolibarr_main_force_https = getenv('FORCE_HTTPS') ? getenv('FORCE_HTTPS') : '0';

// Production Mode: 1 = Error disembunyikan (Aman), 0 = Error ditampilkan (Dev)
$dolibarr_main_prod = getenv('PROD_MODE') ? getenv('PROD_MODE') : '0';

$dolibarr_main_restrict_os_commands = 'mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck = '0';
$dolibarr_main_instance_unique_id = '2d59971a6ef5cb186effce3854c351c7';
$dolibarr_mailing_limit_sendbyweb = '0';
$dolibarr_mailing_limit_sendbycli = '0';

$dolibarr_main_distrib = 'doliwamp';