<?php
//
// File generated by Dolibarr installer
//

// ============================================================================
// BAGIAN 1: KONFIGURASI PATH & AUTO-HEALING (PENYEMBUHAN OTOMATIS)
// ============================================================================

// 1. Tentukan Folder Data (Dokumen)
// Jika di Railway (ada ENV DOLI_DATA_ROOT), pakai itu. Jika tidak, pakai path Windows C:.
$dolibarr_main_data_root = getenv('DOLI_DATA_ROOT') ? getenv('DOLI_DATA_ROOT') : "C:/dolibarr/www/dolibarr/dolibarr_documents";

// 2. Tentukan Folder Dokumen Web (htdocs)
$dolibarr_main_document_root = getenv('DOLI_DOCUMENT_ROOT') ? getenv('DOLI_DOCUMENT_ROOT') : "C:/dolibarr/www/dolibarr/htdocs";

// 3. JURUS AUTO-HEAL: Masalah install.lock
// Cek apakah file install.lock ada. Jika tidak ada (karena tertimpa volume), buat sekarang juga!
$lockfile = $dolibarr_main_data_root . '/install.lock';

// Pastikan foldernya ada dulu sebelum membuat file
if (!is_dir($dolibarr_main_data_root)) {
    @mkdir($dolibarr_main_data_root, 0777, true);
}

// Jika file lock tidak ada, buat file kosong
if (!file_exists($lockfile)) {
    @touch($lockfile);

}

// 4. JURUS AUTO-HEAL: Masalah Izin conf.php
// Cek apakah file ini (conf.php) bisa ditulis. Jika iya, paksa jadi Read-Only (0444).
// Ini akan menghilangkan peringatan keamanan kuning di dashboard.
if (is_writable(__FILE__)) {
    @chmod(__FILE__, 0444);
}

// ============================================================================
// BAGIAN 2: KONFIGURASI URL
// ============================================================================

// URL Utama
$dolibarr_main_url_root = getenv('DOLI_URL_ROOT') ? getenv('DOLI_URL_ROOT') : 'http://localhost/dolibarr';

// URL Custom (Opsional)
$dolibarr_main_url_root_alt = '/custom';
$dolibarr_main_document_root_alt = $dolibarr_main_document_root . '/custom';

// ============================================================================
// BAGIAN 3: KONFIGURASI DATABASE
// ============================================================================

$dolibarr_main_db_host = getenv('DOLI_DB_HOST') ? getenv('DOLI_DB_HOST') : 'localhost';
$dolibarr_main_db_port = getenv('DOLI_DB_PORT') ? getenv('DOLI_DB_PORT') : '3306';
$dolibarr_main_db_name = getenv('DOLI_DB_NAME') ? getenv('DOLI_DB_NAME') : 'dolibarr';
$dolibarr_main_db_user = getenv('DOLI_DB_USER') ? getenv('DOLI_DB_USER') : 'root';
$dolibarr_main_db_pass = getenv('DOLI_DB_PASSWORD') ? getenv('DOLI_DB_PASSWORD') : '';

$dolibarr_main_db_prefix = 'llx_';
$dolibarr_main_db_type = getenv('DOLI_DB_TYPE') ? getenv('DOLI_DB_TYPE') : 'mysqli';
$dolibarr_main_db_character_set = 'utf8';
$dolibarr_main_db_collation = 'utf8_unicode_ci';

// ============================================================================
// BAGIAN 4: KONFIGURASI LAINNYA
// ============================================================================

// Authentication Settings
$dolibarr_main_authentication = getenv('DOLI_AUTH') ? getenv('DOLI_AUTH') : 'dolibarr';

// Security Settings
// Force HTTPS: Jika di Railway (ada ENV URL), paksa HTTPS (1). Jika lokal, biarkan (0).
$dolibarr_main_force_https = getenv('DOLI_URL_ROOT') ? '1' : '0';

// Production Mode: 1 = Sembunyikan Error PHP (Aman), 0 = Tampilkan Error (Dev)
$dolibarr_main_prod = getenv('DOLI_PROD') ? getenv('DOLI_PROD') : '0';

// Command Restrictions
$dolibarr_main_restrict_os_commands = 'mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';

// Misc
$dolibarr_nocsrfcheck = '0';
$dolibarr_main_instance_unique_id = 'unique_id_generated_randomly';
$dolibarr_mailing_limit_sendbyweb = '0';
$dolibarr_mailing_limit_sendbycli = '0';

$dolibarr_main_distrib = 'railway';

?>